### ISSUE TITLE
Only one screenshot for the Turkish store

### ISSUE THREAD

**Issue by bitigchi** [coteditor/Documents-for-AppStore#3]
Hi,

I've noticed the number of screenshots for the Turkish locale decreased to one. Just FYI!

**Comment by 1024jp** [comment]
Oh, thank you for notifying me. Maybe, I miss-operated somewhere... I'll fix it on the next release.

**Comment by 1024jp** [comment]
Fixed on the release of CotEditor 4.1.5.

**Comment by bitigchi** [comment]
どうもありがとう！
